[SOL-401] Reference account IBAN
ivoryio/Ivory pull request #146
Opened 2023-11-16 15:54 UTC by Aligaby

2023-11-21 10:48 UTC, Tudor90 approved these changes

2023-11-22 13:07 UTC, ilie-lupu-ts requested changes

2023-11-22 13:07 UTC, ilie-lupu-ts commented on lib/infrastructure/onboarding/identity_verification/onboarding_identity_verification_service.dart
> +abstract class CreateUrlForIntegrationResponse extends Equatable {
I think that a better name would be `IdentityVerificationServiceResponse`

2023-11-22 13:07 UTC, ilie-lupu-ts commented on lib/infrastructure/onboarding/identity_verification/onboarding_identity_verification_service.dart
> +class CreateUrlForIntegrationSuccesResponse extends CreateUrlForIntegrationResponse {
I would rename these response objects to `CreateIdentificationSuccessResponse` and `CreateIdentificationErrorResponse`

2023-11-22 13:07 UTC, ilie-lupu-ts commented on lib/redux/onboarding/identity_verification/onboarding_identity_verification_action.dart
> +
I would remove the "url for integration" part and have something like `CreateIdentificationCommandAction`, `CreateIdentificationSuccessEventAction`

2023-11-22 13:07 UTC, ilie-lupu-ts commented on lib/screens/onboarding/identity_verification/onboarding_reference_account_iban.dart
> +                                    // Navigator.of(context).pushNamed(NextScreen.routeName);
This comment is not needed, as the navigation to the next step will be done in the `StoreConnector.onWillChange(...)`

2023-11-22 13:46 UTC, ilie-lupu-ts approved these changes

2023-11-22 13:52 UTC, merged