[SOL-238] Transaction approval 3DS
ivoryio/Ivory pull request #72
Opened 2023-08-31 06:31 UTC by ilie-lupu-ts

2023-09-05 12:32 UTC, szaszgyozo requested changes

2023-09-05 12:32 UTC, szaszgyozo commented on lib/infrastructure/device/device_binding_service.dart
> +class BiometricAuthentication {
clasa asta putem scoate daca avem service separat pentru biometrics.

2023-09-05 13:29 UTC, szaszgyozo approved these changes

2023-09-06 07:06 UTC, Tudor90 approved these changes

2023-09-06 07:06 UTC, merged